[project]
name = "CoreService"
version = "0.1.0"
description = "Burda Layihənin Əsas(Core) servisləri olacaq"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.2",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.4",
    "python-dotenv>=1.2.1",
    "ruff>=0.14.5",
    "uvicorn>=0.38.0",
]
